# Welcome to Jekyll!
title: Kirill Markin | Resume | kmarkindev
url:
baseurl:

# Sass setting
sass/style: compressed

# Privacy
open: true                  # show or hide your resume
allow_search_engines: true  # allow your resume indexing by search engine, 'true' or 'false'
description:                # your resume description
open_graph:
  enable: true                        # enable open graph meta tags
  image: null #/assets/images/profile.png   # path or link to the open graph image

# Style
date_format: "%B %d, %Y"     # date format
theme_color: "#1DA1F2"      # your favorite theme color
contact_delimiter: "·"      # contact delimiter, '·', '/' or '|'
section_icon: false          # section title icon, true or false
section_title: uppercase    # section title style, 'uppercase', 'lowercase', 'capitalize' or 'none'
section_align: start        # section title align, 'start', 'end' or 'center'
section_line: solid        # section title line, 'solid', 'dashed' or 'none'
section_background: false   # section title backound, 'true' or 'false'
skill_level_icon: lightbulb # skill rate icon, 'heart', 'star', 'circle' or 'lightbulb'
link_icon: false             # show link icon, 'true' or 'false'
site_footer: false           # show site footer, 'true' or 'false'
site_header: true

# Analytics
analytics:
  google:                   # google
  cloudflare:               # cloudflare
  umami:                    # umami (Replace it with your own)
    script: https://cloud.umami.is/script.js
    website_id: 78a1f8ce-561b-4698-a1c8-04b6ccd57777
    domains: kmarkindev.github.io,kmarkin.dev
